Pregunta;Opción 1;Opción 2;Opción 3;Opción 4;Respuesta Correcta;Referencia
¿Qué es una base de datos relacional?;Una base de datos que organiza los datos en tablas relacionadas entre sí;Una base de datos que almacena datos en documentos JSON;Una base de datos que almacena datos en una sola tabla;Una base de datos que almacena datos en archivos de texto plano;0;https://en.wikipedia.org/wiki/Relational_database
¿Cuál es el componente básico de una base de datos relacional?;Tabla;Documento;Archivo;Registro;0;https://en.wikipedia.org/wiki/Relational_database
¿Qué es una tabla en una base de datos relacional?;Una estructura que organiza los datos en filas y columnas;Una estructura que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/Table_(database)
¿Qué es una clave primaria en una tabla de base de datos relacional?;Un conjunto de uno o más campos que identifican de manera única cada registro en la tabla;Un campo que puede contener valores duplicados en la tabla;Un campo que se usa solo para propósitos de búsqueda rápida;Un campo que se utiliza para almacenar datos en texto plano;0;https://en.wikipedia.org/wiki/Primary_key
¿Qué es una clave foránea (foreign key) en una base de datos relacional?;Un campo en una tabla que hace referencia a la clave primaria de otra tabla;Un campo que almacena valores duplicados en la tabla;Un campo que se usa solo para propósitos de búsqueda rápida;Un campo que se utiliza para almacenar datos en texto plano;0;https://en.wikipedia.org/wiki/Foreign_key
¿Qué es una relación uno a muchos (one-to-many) en una base de datos relacional?;Una relación donde un registro en una tabla puede estar relacionado con varios registros en otra tabla;Una relación donde un registro en una tabla está relacionado con exactamente un registro en otra tabla;Una relación donde un registro en una tabla está relacionado con solo uno de los registros en otra tabla;Una relación donde un registro en una tabla puede tener múltiples campos;0;https://en.wikipedia.org/wiki/One-to-many_(data_model)
¿Qué es una relación muchos a muchos (many-to-many) en una base de datos relacional?;Una relación donde varios registros en una tabla pueden estar relacionados con varios registros en otra tabla;Una relación donde varios registros en una tabla están relacionados con exactamente un registro en otra tabla;Una relación donde varios registros en una tabla están relacionados con solo uno de los registros en otra tabla;Una relación donde varios registros en una tabla pueden tener múltiples campos;0;https://en.wikipedia.org/wiki/Many-to-many_(data_model)
¿Qué es el álgebra relacional en bases de datos?;Un conjunto de operaciones que manipulan tablas para obtener resultados específicos;Un conjunto de operaciones que manipulan documentos JSON;Un conjunto de operaciones que manipulan datos en archivos de texto plano;Un conjunto de operaciones que manipulan datos en una sola tabla;0;https://en.wikipedia.org/wiki/Relational_algebra
¿Qué es una vista (view) en una base de datos relacional?;Una consulta guardada como un objeto en la base de datos;Una tabla que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/View_(SQL)
¿Qué es una transacción en una base de datos relacional?;Una secuencia de operaciones que se ejecutan como una unidad atómica e indivisible;Una operación que se realiza de forma individual en una base de datos relacional;Una operación que no afecta la integridad de los datos en una base de datos relacional;Una operación que solo se realiza con documentos JSON;0;https://en.wikipedia.org/wiki/Database_transaction
¿Qué es la normalización en el contexto de las bases de datos relacionales?;Un proceso para organizar datos en tablas para reducir la redundancia y mejorar la integridad de los datos;Un proceso para almacenar datos en documentos JSON;Un proceso para almacenar datos en archivos de texto plano;Un proceso para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Database_normalization
¿Qué es la denormalización en el contexto de las bases de datos relacionales?;Un proceso para aumentar el rendimiento al reducir la normalización de los datos;Un proceso para organizar datos en tablas para reducir la redundancia y mejorar la integridad de los datos;Un proceso para almacenar datos en documentos JSON;Un proceso para almacenar datos en archivos de texto plano;0;https://en.wikipedia.org/wiki/Denormalization
¿Qué es SQL (Structured Query Language)?;Un lenguaje de programación utilizado para gestionar datos en bases de datos relacionales;Un lenguaje de programación utilizado para gestionar documentos JSON;Un lenguaje de programación utilizado para gestionar archivos de texto plano;Un lenguaje de programación utilizado para gestionar datos en una sola tabla;0;https://en.wikipedia.org/wiki/SQL
¿Qué es una consulta SQL (SQL query)?;Una instrucción utilizada para recuperar datos de una base de datos relacional;Una instrucción utilizada para almacenar documentos JSON;Una instrucción utilizada para almacenar datos en archivos de texto plano;Una instrucción utilizada para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/SQL_syntax
¿Qué es un índice en una base de datos relacional?;Una estructura que mejora la velocidad de búsqueda de registros en una tabla;Una estructura que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola tabla;0;https://en.wikipedia.org/wiki/Database_index
¿Qué es un disparador (trigger) en una base de datos relacional?;Un procedimiento almacenado que se ejecuta automáticamente cuando se realiza una operación específica en la base de datos;Una tabla que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola tabla;0;https://en.wikipedia.org/wiki/Database_trigger
¿Qué es la integridad referencial en una base de datos relacional?;La precisión y consistencia de los datos entre tablas relacionadas mediante claves foráneas;La precisión y consistencia de los datos en una sola tabla;La precisión y consistencia de los datos en documentos JSON;La precisión y consistencia de los datos en archivos de texto plano;0;https://en.wikipedia.org/wiki/Referential_integrity
¿Qué es un modelo entidad-relación (ER)?;Un modelo conceptual utilizado para describir los datos y sus relaciones en una base de datos;Un modelo para almacenar datos en documentos JSON;Un modelo para almacenar datos en archivos de texto plano;Un modelo para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model
¿Qué es un modelo relacional?;Un modelo de datos que organiza los datos en tablas relacionadas entre sí;Un modelo para almacenar datos en documentos JSON;Un modelo para almacenar datos en archivos de texto plano;Un modelo para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Relational_model
¿Qué es el álgebra relacional en bases de datos?;Un conjunto de operaciones que manipulan tablas para obtener resultados específicos;Un conjunto de operaciones que manipulan documentos JSON;Un conjunto de operaciones que manipulan datos en archivos de texto plano;Un conjunto de operaciones que manipulan datos en una sola tabla;0;https://en.wikipedia.org/wiki/Relational_algebra
¿Qué es una vista materializada (materialized view) en una base de datos relacional?;Una vista que almacena físicamente los resultados de una consulta para mejorar el rendimiento de consultas repetitivas;Una tabla que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/Materialized_view
¿Qué es la concurrencia en una base de datos relacional?;La capacidad de manejar múltiples transacciones simultáneamente de manera segura y eficiente;La capacidad de manejar una sola transacción de manera segura y eficiente;La capacidad de manejar solo consultas SELECT de manera segura y eficiente;La capacidad de manejar datos en documentos JSON de manera segura y eficiente;0;https://en.wikipedia.org/wiki/Concurrency_control
¿Qué es la atomicidad en una base de datos relacional?;La propiedad que garantiza que una transacción se realiza como una unidad atómica e indivisible;La propiedad que garantiza la precisión de los datos en una sola tabla;La propiedad que garantiza que los datos en documentos JSON sean precisos;La propiedad que garantiza que los datos en archivos de texto plano sean precisos;0;https://en.wikipedia.org/wiki/Atomicity_(database_systems)
¿Qué es la consistencia en una base de datos relacional?;La propiedad que garantiza que solo los datos válidos se pueden almacenar en la base de datos;La propiedad que garantiza que una transacción se realiza como una unidad atómica e indivisible;La propiedad que garantiza la precisión de los datos en una sola tabla;La propiedad que garantiza que los datos en documentos JSON sean precisos;0;https://en.wikipedia.org/wiki/Consistency_(database_systems)
¿Qué es el aislamiento en una base de datos relacional?;La propiedad que garantiza que una transacción no vea los cambios de otras transacciones hasta que se completen;La propiedad que garantiza la precisión de los datos en una sola tabla;La propiedad que garantiza que los datos en documentos JSON sean precisos;La propiedad que garantiza que los datos en archivos de texto plano sean precisos;0;https://en.wikipedia.org/wiki/Isolation_(database_systems)
¿Qué es la durabilidad en una base de datos relacional?;La propiedad que garantiza que los cambios realizados por una transacción persisten incluso en caso de fallo del sistema;La propiedad que garantiza la precisión de los datos en una sola tabla;La propiedad que garantiza que los datos en documentos JSON sean precisos;La propiedad que garantiza que los datos en archivos de texto plano sean precisos;0;https://en.wikipedia.org/wiki/Durability_(database_systems)
¿Qué es el modelo ACID en el contexto de las bases de datos relacionales?;Un conjunto de propiedades que garantizan la integridad de las transacciones: Atomicidad, Consistencia, Aislamiento y Durabilidad;Un conjunto de operaciones que manipulan tablas para obtener resultados específicos;Un conjunto de operaciones que manipulan datos en archivos de texto plano;Un conjunto de operaciones que manipulan datos en una sola tabla;0;https://en.wikipedia.org/wiki/ACID
¿Qué es un JOIN en SQL?;Una operación que combina filas de dos o más tablas según una condición relacionada;Una operación que almacena documentos JSON;Una operación que almacena datos en archivos de texto plano;Una operación que almacena datos en una sola tabla;0;https://en.wikipedia.org/wiki/Join_(SQL)
¿Qué es un índice único (unique index) en una base de datos relacional?;Un índice que asegura que no puede haber valores duplicados en una columna específica de una tabla;Un índice que almacena documentos JSON;Un índice que almacena datos en archivos de texto plano;Un índice que almacena datos en una sola tabla;0;https://en.wikipedia.org/wiki/Unique_key
¿Qué es un índice compuesto (composite index) en una base de datos relacional?;Un índice que incluye múltiples columnas para mejorar el rendimiento de consultas que utilizan esas columnas juntas;Un índice que almacena documentos JSON;Un índice que almacena datos en archivos de texto plano;Un índice que almacena datos en una sola tabla;0;https://en.wikipedia.org/wiki/Composite_index
¿Qué es la normalización en el contexto de las bases de datos relacionales?;Un proceso para organizar datos en tablas para reducir la redundancia y mejorar la integridad de los datos;Un proceso para almacenar datos en documentos JSON;Un proceso para almacenar datos en archivos de texto plano;Un proceso para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Database_normalization
¿Qué es un cursor en el contexto de bases de datos relacionales?;Un objeto utilizado para recorrer y procesar filas individuales devueltas por una consulta SQL;Un objeto utilizado para almacenar documentos JSON;Un objeto utilizado para almacenar datos en archivos de texto plano;Un objeto utilizado para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Cursor_(databases)
¿Qué es una transacción en el contexto de las bases de datos relacionales?;Una secuencia de operaciones que se ejecutan como una unidad atómica e indivisible;Una operación que se realiza de forma individual en una base de datos relacional;Una operación que no afecta la integridad de los datos en una base de datos relacional;Una operación que solo se realiza con documentos JSON;0;https://en.wikipedia.org/wiki/Database_transaction
¿Qué es el álgebra relacional en bases de datos?;Un conjunto de operaciones que manipulan tablas para obtener resultados específicos;Un conjunto de operaciones que manipulan documentos JSON;Un conjunto de operaciones que manipulan datos en archivos de texto plano;Un conjunto de operaciones que manipulan datos en una sola tabla;0;https://en.wikipedia.org/wiki/Relational_algebra
¿Qué es una vista (view) en una base de datos relacional?;Una consulta guardada como un objeto en la base de datos;Una tabla que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/View_(SQL)
¿Qué es una vista materializada (materialized view) en una base de datos relacional?;Una vista que almacena físicamente los resultados de una consulta para mejorar el rendimiento de consultas repetitivas;Una tabla que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/Materialized_view
¿Qué es un disparador (trigger) en una base de datos relacional?;Un procedimiento almacenado que se ejecuta automáticamente cuando se realiza una operación específica en la base de datos;Una tabla que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/Database_trigger
¿Qué es un índice en una base de datos relacional?;Una estructura que mejora la velocidad de búsqueda de registros en una tabla;Una estructura que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/Database_index
¿Qué es la integridad referencial en una base de datos relacional?;La precisión y consistencia de los datos entre tablas relacionadas mediante claves foráneas;La precisión y consistencia de los datos en una sola tabla;La precisión y consistencia de los datos en documentos JSON;La precisión y consistencia de los datos en archivos de texto plano;0;https://en.wikipedia.org/wiki/Referential_integrity
¿Qué es un modelo entidad-relación (ER)?;Un modelo conceptual utilizado para describir los datos y sus relaciones en una base de datos;Un modelo para almacenar datos en documentos JSON;Un modelo para almacenar datos en archivos de texto plano;Un modelo para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model
¿Qué es un modelo relacional?;Un modelo de datos que organiza los datos en tablas relacionadas entre sí;Un modelo para almacenar datos en documentos JSON;Un modelo para almacenar datos en archivos de texto plano;Un modelo para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Relational_model
¿Qué es el álgebra relacional en bases de datos?;Un conjunto de operaciones que manipulan tablas para obtener resultados específicos;Un conjunto de operaciones que manipulan documentos JSON;Un conjunto de operaciones que manipulan datos en archivos de texto plano;Un conjunto de operaciones que manipulan datos en una sola tabla;0;https://en.wikipedia.org/wiki/Relational_algebra
¿Qué es una consulta SQL (SQL query)?;Una instrucción utilizada para recuperar datos de una base de datos relacional;Una instrucción utilizada para almacenar documentos JSON;Una instrucción utilizada para almacenar datos en archivos de texto plano;Una instrucción utilizada para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/SQL_syntax
¿Qué es un JOIN en SQL?;Una operación que combina filas de dos o más tablas según una condición relacionada;Una operación que almacena documentos JSON;Una operación que almacena datos en archivos de texto plano;Una operación que almacena datos en una sola tabla;0;https://en.wikipedia.org/wiki/Join_(SQL)
¿Qué es un índice único (unique index) en una base de datos relacional?;Un índice que asegura que no puede haber valores duplicados en una columna específica de una tabla;Un índice que almacena documentos JSON;Un índice que almacena datos en archivos de texto plano;Un índice que almacena datos en una sola tabla;0;https://en.wikipedia.org/wiki/Unique_key
¿Qué es un índice compuesto (composite index) en una base de datos relacional?;Un índice que incluye múltiples columnas para mejorar el rendimiento de consultas que utilizan esas columnas juntas;Un índice que almacena documentos JSON;Un índice que almacena datos en archivos de texto plano;Un índice que almacena datos en una sola tabla;0;https://en.wikipedia.org/wiki/Composite_index
¿Qué es la normalización en el contexto de las bases de datos relacionales?;Un proceso para organizar datos en tablas para reducir la redundancia y mejorar la integridad de los datos;Un proceso para almacenar datos en documentos JSON;Un proceso para almacenar datos en archivos de texto plano;Un proceso para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Database_normalization
¿Qué es un cursor en el contexto de bases de datos relacionales?;Un objeto utilizado para recorrer y procesar filas individuales devueltas por una consulta SQL;Un objeto utilizado para almacenar documentos JSON;Un objeto utilizado para almacenar datos en archivos de texto plano;Un objeto utilizado para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Cursor_(databases)
¿Qué es una transacción en el contexto de las bases de datos relacionales?;Una secuencia de operaciones que se ejecutan como una unidad atómica e indivisible;Una operación que se realiza de forma individual en una base de datos relacional;Una operación que no afecta la integridad de los datos en una base de datos relacional;Una operación que solo se realiza con documentos JSON;0;https://en.wikipedia.org/wiki/Database_transaction
¿Qué es el álgebra relacional en bases de datos?;Un conjunto de operaciones que manipulan tablas para obtener resultados específicos;Un conjunto de operaciones que manipulan documentos JSON;Un conjunto de operaciones que manipulan datos en archivos de texto plano;Un conjunto de operaciones que manipulan datos en una sola tabla;0;https://en.wikipedia.org/wiki/Relational_algebra
¿Qué es una vista (view) en una base de datos relacional?;Una consulta guardada como un objeto en la base de datos;Una tabla que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/View_(SQL)
¿Qué es una vista materializada (materialized view) en una base de datos relacional?;Una vista que almacena físicamente los resultados de una consulta para mejorar el rendimiento de consultas repetitivas;Una tabla que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/Materialized_view
¿Qué es un disparador (trigger) en una base de datos relacional?;Un procedimiento almacenado que se ejecuta automáticamente cuando se realiza una operación específica en la base de datos;Una tabla que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/Database_trigger
¿Qué es un índice en una base de datos relacional?;Una estructura que mejora la velocidad de búsqueda de registros en una tabla;Una estructura que almacena documentos JSON;Una estructura que almacena datos en archivos de texto plano;Una estructura que almacena datos en una sola fila;0;https://en.wikipedia.org/wiki/Database_index
¿Qué es la integridad referencial en una base de datos relacional?;La precisión y consistencia de los datos entre tablas relacionadas mediante claves foráneas;La precisión y consistencia de los datos en una sola tabla;La precisión y consistencia de los datos en documentos JSON;La precisión y consistencia de los datos en archivos de texto plano;0;https://en.wikipedia.org/wiki/Referential_integrity
¿Qué es un modelo entidad-relación (ER)?;Un modelo conceptual utilizado para describir los datos y sus relaciones en una base de datos;Un modelo para almacenar datos en documentos JSON;Un modelo para almacenar datos en archivos de texto plano;Un modelo para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model
¿Qué es un modelo relacional?;Un modelo de datos que organiza los datos en tablas relacionadas entre sí;Un modelo para almacenar datos en documentos JSON;Un modelo para almacenar datos en archivos de texto plano;Un modelo para almacenar datos en una sola tabla;0;https://en.wikipedia.org/wiki/Relational_model
